### PR TITLE
Ensure that CreateSupportRequest doesn't leave DB in inconsistent state 262

### LINKED ISSUE #262: Bug in MAC user all support requests view
Currently, when a MAC user is on the dashboard and selects the view for "all support requests", the link in the row for the support request is broken

image

image

### PR DESCRIPTION
**Pull request by kyaroch**
## Changelog
- Improved error handling in `CreateSupportRequest` action so that transaction is rolled back if any part of it fails
- Added validations to `LockboxTransaction`
- Ensured that transactions are always saved with a category
- Updated specs

## Link to issue:  
Fixes #262 

## Steps for QA/Special Notes:
- Tested support request creation (both through console and actual form) and verified that it still works

## Relevant Screenshots: 
- N/A

## Are you ready for review?:

- [x] Added relevant tests
- [x] Linked PR to the issue
- [x] Added notes for QA/special notes
- [ ] Added revelant screenshots

### CODE REVIEW

File: spec/lib/create_support_request_spec.rb [hunk 1]
```diff
@@ -16,27 +26,68 @@
...
+  context "when one of the lockbox transactions is invalid" do
+    let(:lockbox_transactions) do
+      [
+        {
+          amount:   42.42,
+          category: "gas"
+        },
+        {
+          amount:   0.00
+        }
```
Comment (BintLopez) [inline spec/lib/create_support_request_spec.rb]: In this case, can we also add a transaction with a `category` but `""` for an amount?

File: spec/models/lockbox_action_spec.rb [hunk 2]
```diff
@@ -37,7 +37,7 @@
       FactoryBot.create(:lockbox_action, :support_client).tap do |action|
         action.lockbox_transactions.create(
           amount_cents: 20_00,
-          category: 'gas'
+          category: LockboxTransaction::GAS
```
Comment (BintLopez) [inline spec/models/lockbox_action_spec.rb]: 🚗

File: spec/models/lockbox_partner_spec.rb [hunk 3]
```diff
@@ -14,7 +14,8 @@ def add_cash(partner, date)
     ).tap do |action|
       action.lockbox_transactions.create!(
         amount_cents: 1000_00,
-        balance_effect: 'credit'
+        balance_effect: 'credit',
```
Comment (BintLopez) [inline spec/models/lockbox_partner_spec.rb]: wanna constantize this one while we're here? `LockboxTransaction::CREDIT`

File: spec/models/lockbox_partner_spec.rb [hunk 4]
```diff
@@ -28,7 +29,8 @@ def pending_request_on(partner, date, amount_breakdown)
       amount_breakdown.each do |amt_cents|
         lb_action.lockbox_transactions.create!(
           amount_cents: amt_cents,
-          balance_effect: 'debit'
+          balance_effect: 'debit',
```
Comment (BintLopez) [inline spec/models/lockbox_partner_spec.rb]: and ditto.... `LockboxTransaction::DEBIT`

File: spec/lib/create_support_request_spec.rb (hunk 1 above)
Comment (kyaroch) [reply spec/lib/create_support_request_spec.rb]: In the same test, that wouldn't have any effect, as only one needs to be invalid. I did add another test where both are blank, to verify that we're ignoring that transaction.
